const TECH_CATEGORIES = [
  {
    label: 'Languages',
    items: [
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'C#',
      '.NET',
      'C++',
      'C',
      'Go',
      'Golang',
      'Rust',
      'SQL',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'Dart',
      'Scala',
      'Elixir',
      'Haskell',
      'Clojure',
      'Lua',
      'Perl',
      'R',
      'Julia',
      'Solidity',
      'Bash',
      'PowerShell',
      'VBA',
      'Groovy',
      'Apex',
      'Assembly',
      'COBOL',
      'Fortran',
      'MATLAB',
    ],
  },
  {
    label: 'AI & ML',
    items: [
      'OpenAI',
      'Anthropic',
      'LangChain',
      'LangGraph',
      'LlamaIndex',
      'PyTorch',
      'TensorFlow',
      'Scikit-learn',
      'Pandas',
      'NumPy',
      'OpenCV',
      'Keras',
      'Hugging Face',
      'Generative AI',
      'LLM',
      'LLMs',
      'RAG',
      'Prompt Engineering',
      'Agentic AI',
      'AI Agents',
      'Vector Database',
      'Pinecone',
      'ChromaDB',
      'Qdrant',
      'Milvus',
      'pgvector',
      'Databricks',
      'LLMOps',
    ],
  },
  {
    label: 'Frontend',
    items: [
      'React',
      'React.js',
      'Angular',
      'Vue',
      'Vue.js',
      'Next.js',
      'Nuxt',
      'Nuxt.js',
      'Svelte',
      'SvelteKit',
      'SolidJS',
      'Astro',
      'Redux',
      'Redux Toolkit',
      'Zustand',
      'MobX',
      'Recoil',
      'Jotai',
      'TanStack Query',
      'React Query',
      'Pinia',
      'Vuex',
      'NgRx',
      'Tailwind CSS',
      'Tailwind',
      'Shadcn',
      'Shadcn UI',
      'Chakra UI',
      'Material UI',
      'MUI',
      'Ant Design',
      'Radix UI',
      'Bootstrap',
      'Sass',
      'SCSS',
      'HTML',
      'HTML5',
      'CSS',
      'CSS3',
      'Webpack',
      'Vite',
      'Babel',
      'jQuery',
      'RxJS',
      'XState',
    ],
  },
  {
    label: 'Backend & DB',
    items: [
      'Node.js',
      'Express',
      'Express.js',
      'NestJS',
      'Django',
      'Flask',
      'FastAPI',
      'Spring',
      'Spring Boot',
      'ASP.NET',
      'Laravel',
      'Symfony',
      'Ruby on Rails',
      'Rails',
      'GraphQL',
      'REST API',
      'gRPC',
      'WebSockets',
      'PostgreSQL',
      'Postgres',
      'MongoDB',
      'Redis',
      'MySQL',
      'SQLite',
      'Oracle',
      'Microsoft SQL Server',
      'MS SQL',
      'MariaDB',
      'Elasticsearch',
      'Cassandra',
      'DynamoDB',
      'Supabase',
      'Firebase',
      'ClickHouse',
      'Prisma',
      'Sequelize',
      'TypeORM',
      'Hibernate',
    ],
  },
  {
    label: 'System Design',
    items: [
      'System Design',
      'Microservices',
      'Event-Driven Architecture',
      'Domain-Driven Design',
      'DDD',
      'Clean Architecture',
      'Monolith',
      'Serverless',
      'CQRS',
      'API Design',
      'Design Patterns',
      'Distributed Systems',
      'Load Balancing',
      'Service Mesh',
    ],
  },
  {
    label: 'Data & BI',
    items: [
      'Snowflake',
      'Databricks',
      'BigQuery',
      'Redshift',
      'Apache Spark',
      'Spark',
      'Apache Airflow',
      'Airflow',
      'dbt',
      'Power BI',
      'Tableau',
      'Looker',
      'ETL',
      'Data Warehousing',
      'Data Lake',
      'ClickHouse',
      'Presto',
      'Trino',
      'Kafka',
      'Hadoop',
      'Data Contracts',
      'Data Pipelines',
    ],
  },
  {
    label: 'Cloud',
    items: [
      'AWS',
      'Azure',
      'GCP',
      'Google Cloud',
      'OpenStack',
      'Cloudflare',
      'Vercel',
      'Netlify',
      'Fastly',
      'VMware',
      'VirtualBox',
      'Proxmox',
      'Linux',
      'Unix',
    ],
  },
  {
    label: 'DevOps',
    items: [
      'Terraform',
      'Kubernetes',
      'K8s',
      'Docker',
      'CI/CD',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI',
      'CircleCI',
      'ArgoCD',
      'Ansible',
      'Puppet',
      'Chef',
      'CloudFormation',
      'Pulumi',
      'Helm',
      'Nginx',
      'Apache',
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
    ],
  },
  {
    label: 'Security',
    items: [
      'Cybersecurity',
      'SIEM',
      'DevSecOps',
      'Datadog',
      'Splunk',
      'Prometheus',
      'Grafana',
      'SOC2',
      'ISO27001',
      'HIPAA',
      'GDPR',
      'DORA',
      'Penetration Testing',
      'Metasploit',
      'Wireshark',
      'Burp Suite',
      'IAM',
      'Zero Trust',
      'Incident Response',
    ],
  },
  {
    label: 'Automation',
    items: [
      'n8n',
      'Zapier',
      'Make',
      'Clay',
      'Retool',
      'Workato',
      'UiPath',
      'Power Automate',
      'Automation Anywhere',
      'Blue Prism',
      'Activepieces',
      'Pipedream',
      'Bardeen',
      'Appsmith',
      'Bubble',
      'Webflow',
      'FlutterFlow',
      'Glide',
      'Softr',
      'Nintex',
    ],
  },
  {
    label: 'Design',
    items: [
      'Figma',
      'Adobe XD',
      'Sketch',
      'Photoshop',
      'Illustrator',
      'InDesign',
      'Canva',
      'Framer',
      'Penpot',
      'InVision',
      'Zeplin',
      'CorelDRAW',
      'Affinity Designer',
      'Procreate',
      'Spline',
      'Rive',
      'Lottie',
    ],
  },
  {
    label: 'Video',
    items: [
      'Premiere Pro',
      'After Effects',
      'DaVinci Resolve',
      'Final Cut Pro',
      'CapCut',
      'Adobe Audition',
      'Blender',
      'Cinema 4D',
      'Maya',
      'Houdini',
      'Nuke',
      'Runway',
      'Topaz Video AI',
    ],
  },
  {
    label: 'Game Dev',
    items: [
      'Unreal Engine',
      'Unity',
      'Godot',
      'Cocos2d',
      'OpenGL',
      'DirectX',
      'Vulkan',
      'WebGL',
      'Three.js',
      'Shader',
      'HLSL',
      'GLSL',
    ],
  },
  {
    label: 'Mobile',
    items: [
      'Flutter',
      'React Native',
      'iOS',
      'Android',
      'SwiftUI',
      'Jetpack Compose',
      'Expo',
      'Capacitor',
      'Kotlin Multiplatform',
      'KMP',
      'Ionic',
      'Xamarin',
      'Cordova',
      'NativeScript',
    ],
  },
  {
    label: 'Embedded & IoT',
    items: [
      'Embedded C',
      'Embedded C++',
      'RTOS',
      'FreeRTOS',
      'Microcontrollers',
      'ARM',
      'FPGA',
      'Verilog',
      'VHDL',
      'Arduino',
      'Raspberry Pi',
      'ESP32',
      'Firmware',
      'PCB Design',
    ],
  },
  {
    label: 'Web3',
    items: [
      'Solidity',
      'EVM',
      'Ethereum',
      'Bitcoin',
      'Web3.js',
      'Ethers.js',
      'Hardhat',
      'Truffle',
      'Smart Contracts',
      'DeFi',
      'NFT',
      'Cosmos',
      'Polkadot',
    ],
  },
  {
    label: 'QA & Testing',
    items: [
      'Jest',
      'Mocha',
      'Chai',
      'Cypress',
      'Playwright',
      'Selenium',
      'Puppeteer',
      'Appium',
      'JUnit',
      'TestNG',
      'PyTest',
      'Cucumber',
      'Postman',
      'JMeter',
      'BrowserStack',
      'Sauce Labs',
    ],
  },
  {
    label: 'Product & Agile',
    items: [
      'Product Management',
      'Agile',
      'Scrum',
      'Kanban',
      'Roadmapping',
      'Product Strategy',
      'User Research',
      'A/B Testing',
      'Mixpanel',
      'Amplitude',
      'PostHog',
      'Jira',
      'Confluence',
    ],
  },
  {
    label: 'Marketing',
    items: [
      'SEO',
      'SEM',
      'Google Analytics',
      'GA4',
      'Google Ads',
      'Meta Ads',
      'Growth Hacking',
      'Content Strategy',
      'Email Marketing',
      'Klaviyo',
      'Mailchimp',
      'CRO',
    ],
  },
  {
    label: 'HR & People',
    items: [
      'Workday',
      'BambooHR',
      'Greenhouse',
      'Lever',
      'Rippling',
      'Gusto',
      'ATS',
      'Talent Acquisition',
      'Payroll',
      'HRIS',
      'Recruiting',
    ],
  },
  {
    label: 'Fintech',
    items: [
      'Stripe',
      'Plaid',
      'QuickBooks',
      'NetSuite',
      'Xero',
      'Financial Modeling',
      'Fintech',
      'Payment Gateways',
      'RegTech',
      'Ledger',
      'Accounting',
    ],
  },
  {
    label: 'Enterprise',
    items: [
      'Salesforce',
      'HubSpot',
      'Shopify',
      'WordPress',
      'WooCommerce',
      'Magento',
      'ServiceNow',
      'SAP',
    ],
  },
];

const TECH_KEYWORDS = TECH_CATEGORIES.flatMap((category) => category.items);

const TECH_CATEGORY_MAP = Object.fromEntries(
  TECH_CATEGORIES.flatMap((category) => category.items.map((entry) => [entry, category.label])).map(
    ([name, label]) => [name.toLowerCase(), label],
  ),
);

if (typeof globalThis !== 'undefined') {
  globalThis.TECH_CATEGORIES = TECH_CATEGORIES;
  globalThis.TECH_KEYWORDS = TECH_KEYWORDS;
  globalThis.TECH_CATEGORY_MAP = TECH_CATEGORY_MAP;
  if (typeof globalThis.module !== 'undefined') {
    globalThis.module.exports = {
      TECH_CATEGORIES,
      TECH_KEYWORDS,
      TECH_CATEGORY_MAP,
    };
  }
}
