const TECH_CATEGORIES = [
  {
    label: 'Languages',
    items: [
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'C#',
      '.NET',
      'C++',
      'C',
      'Go',
      'Golang',
      'Rust',
      'SQL',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'Dart',
      'Scala',
      'Elixir',
      'Haskell',
      'Clojure',
      'Lua',
      'Perl',
      'R',
      'Julia',
      'Solidity',
      'Bash',
      'PowerShell',
      'VBA',
      'Groovy',
      'Apex',
      'Assembly',
      'COBOL',
      'Fortran',
      'MATLAB',
    ],
  },
  {
    label: 'AI & ML',
    items: [
      // APIs & Providers
      'OpenAI',
      'Anthropic',
      'Claude',
      'Gemini',
      'Mistral',
      'Cohere',
      'Perplexity',
      'ChatGPT',
      'GPT-4',
      'GPT-4o',
      // Frameworks
      'LangChain',
      'LangGraph',
      'LlamaIndex',
      'CrewAI',
      'AutoGen',
      'DSPy',
      'Haystack',
      'Semantic Kernel',
      // ML Frameworks
      'PyTorch',
      'TensorFlow',
      'Scikit-learn',
      'Keras',
      'JAX',
      'XGBoost',
      'LightGBM',
      'CatBoost',
      // Data Science
      'Pandas',
      'NumPy',
      'OpenCV',
      'Matplotlib',
      'Seaborn',
      'SciPy',
      'Jupyter',
      'Hugging Face',
      'Transformers',
      'Diffusers',
      // Vector Databases
      'Pinecone',
      'ChromaDB',
      'Qdrant',
      'Milvus',
      'Weaviate',
      'pgvector',
      'LanceDB',
      // Platforms & MLOps
      'Databricks',
      'MLflow',
      'Weights & Biases',
      'W&B',
      'Neptune',
      'SageMaker',
      'Vertex AI',
      'Azure ML',
      'H2O.ai',
      'Dataiku',
      'BentoML',
      'Seldon',
      'Ray',
      // Concepts
      'Generative AI',
      'LLM',
      'LLMs',
      'RAG',
      'RLHF',
      'Fine-tuning',
      'Prompt Engineering',
      'Agentic AI',
      'AI Agents',
      'Multi-Agent',
      'Vector Database',
      'Embeddings',
      'LLMOps',
      'MLOps',
      'NLP',
      'Computer Vision',
      'Recommendation Systems',
    ],
  },
  {
    label: 'Frontend',
    items: [
      'React',
      'React.js',
      'Angular',
      'Vue',
      'Vue.js',
      'Next.js',
      'Nuxt',
      'Nuxt.js',
      'Svelte',
      'SvelteKit',
      'SolidJS',
      'Astro',
      'Redux',
      'Redux Toolkit',
      'Zustand',
      'MobX',
      'Recoil',
      'Jotai',
      'TanStack Query',
      'React Query',
      'Pinia',
      'Vuex',
      'NgRx',
      'Tailwind CSS',
      'Tailwind',
      'Shadcn',
      'Shadcn UI',
      'Chakra UI',
      'Material UI',
      'MUI',
      'Ant Design',
      'Radix UI',
      'Bootstrap',
      'Sass',
      'SCSS',
      'HTML',
      'HTML5',
      'CSS',
      'CSS3',
      'Webpack',
      'Vite',
      'Babel',
      'jQuery',
      'RxJS',
      'XState',
    ],
  },
  {
    label: 'Backend & DB',
    items: [
      'Node.js',
      'Express',
      'Express.js',
      'NestJS',
      'Django',
      'Flask',
      'FastAPI',
      'Spring',
      'Spring Boot',
      'ASP.NET',
      'Laravel',
      'Symfony',
      'Ruby on Rails',
      'Rails',
      'GraphQL',
      'REST API',
      'gRPC',
      'WebSockets',
      'PostgreSQL',
      'Postgres',
      'MongoDB',
      'Redis',
      'MySQL',
      'SQLite',
      'Oracle',
      'Microsoft SQL Server',
      'MS SQL',
      'MariaDB',
      'Elasticsearch',
      'Cassandra',
      'DynamoDB',
      'Supabase',
      'Firebase',
      'ClickHouse',
      'Prisma',
      'Sequelize',
      'TypeORM',
      'Hibernate',
    ],
  },
  {
    label: 'System Design',
    items: [
      'System Design',
      'Microservices',
      'Event-Driven Architecture',
      'Domain-Driven Design',
      'DDD',
      'Clean Architecture',
      'Monolith',
      'Serverless',
      'CQRS',
      'API Design',
      'Design Patterns',
      'Distributed Systems',
      'Load Balancing',
      'Service Mesh',
    ],
  },
  {
    label: 'Data & BI',
    items: [
      // Cloud Warehouses
      'Snowflake',
      'Databricks',
      'BigQuery',
      'Redshift',
      'Azure Synapse',
      // Compute & Processing
      'Apache Spark',
      'Spark',
      'Apache Flink',
      'Flink',
      'Apache Beam',
      'Apache Hadoop',
      'Hadoop',
      'Presto',
      'Trino',
      'ClickHouse',
      'DuckDB',
      // Orchestration
      'Apache Airflow',
      'Airflow',
      'Prefect',
      'Dagster',
      'Luigi',
      'dbt',
      'dbt Cloud',
      // Streaming
      'Kafka',
      'Apache Kafka',
      'Kinesis',
      'Pub/Sub',
      'RabbitMQ',
      'Debezium',
      // BI & Visualization
      'Power BI',
      'Tableau',
      'Looker',
      'Looker Studio',
      'Metabase',
      'Superset',
      'Apache Superset',
      'Grafana',
      'QuickSight',
      'Mode Analytics',
      'Hex',
      'Observable',
      // Data Quality & Catalog
      'Great Expectations',
      'Monte Carlo',
      'Atlan',
      'Alation',
      'Collibra',
      'DataHub',
      'Amundsen',
      'dbt tests',
      // Data Ingestion / Integration
      'Fivetran',
      'Airbyte',
      'Stitch',
      'Talend',
      'Informatica',
      'Azure Data Factory',
      'AWS Glue',
      'Google Dataflow',
      // Storage
      'Delta Lake',
      'Apache Iceberg',
      'Apache Hudi',
      // Analytics
      'Alteryx',
      'SAS',
      'SPSS',
      'RStudio',
      // Concepts
      'ETL',
      'ELT',
      'Data Warehousing',
      'Data Lake',
      'Data Lakehouse',
      'Data Mesh',
      'Data Contracts',
      'Data Pipelines',
      'Data Governance',
      'Data Modeling',
      'OLAP',
      'Dimensional Modeling',
      'Star Schema',
      // Languages & Tools
      'PySpark',
      'Pandas',
      'NumPy',
      'Jupyter',
      'Excel',
      'SQL',
    ],
  },
  {
    label: 'Cloud',
    items: [
      'AWS',
      'Azure',
      'GCP',
      'Google Cloud',
      'OpenStack',
      'Cloudflare',
      'Vercel',
      'Netlify',
      'Fastly',
      'VMware',
      'VirtualBox',
      'Proxmox',
      'Linux',
      'Unix',
    ],
  },
  {
    label: 'DevOps',
    items: [
      'Terraform',
      'Kubernetes',
      'K8s',
      'Docker',
      'CI/CD',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI',
      'CircleCI',
      'ArgoCD',
      'Ansible',
      'Puppet',
      'Chef',
      'CloudFormation',
      'Pulumi',
      'Helm',
      'Nginx',
      'Apache',
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
    ],
  },
  {
    label: 'Security',
    items: [
      // Domains
      'Cybersecurity',
      'Application Security',
      'Cloud Security',
      'Network Security',
      'Zero Trust',
      'DevSecOps',
      'Penetration Testing',
      'Pen Testing',
      'Red Team',
      'Blue Team',
      'Threat Modeling',
      'Incident Response',
      'Vulnerability Management',
      'Security Architecture',
      // SIEM & Monitoring
      'SIEM',
      'Splunk',
      'Datadog',
      'Prometheus',
      'Grafana',
      'Elastic SIEM',
      'Microsoft Sentinel',
      'Chronicle',
      'QRadar',
      // Offensive Security
      'Metasploit',
      'Burp Suite',
      'Wireshark',
      'Nmap',
      'Nessus',
      'Kali Linux',
      'OWASP',
      'Nuclei',
      // Identity & Access
      'IAM',
      'Okta',
      'Azure AD',
      'CyberArk',
      'HashiCorp Vault',
      'OAuth',
      'SAML',
      'SSO',
      'MFA',
      'PAM',
      // Cloud Security
      'AWS GuardDuty',
      'AWS Security Hub',
      'Wiz',
      'Orca Security',
      'Prisma Cloud',
      'Lacework',
      // Endpoint & EDR
      'CrowdStrike',
      'SentinelOne',
      'Carbon Black',
      'Microsoft Defender',
      // SOAR & Detection
      'SOAR',
      'SAST',
      'DAST',
      'SCA',
      'Snyk',
      'Semgrep',
      'Trivy',
      'Tenable',
      'Qualys',
      'Falco',
      // Frameworks
      'MITRE ATT&CK',
      'STRIDE',
      'SBOM',
      'YARA',
      'Sigma',
      'OWASP',
      'SOC2',
      'ISO27001',
      'HIPAA',
      'GDPR',
      'DORA',
      'NIST',
      'PCI DSS',
      'FedRAMP',
      'CCPA',
    ],
  },
  {
    label: 'Automation',
    items: [
      'n8n',
      'Zapier',
      'Make',
      'Clay',
      'Retool',
      'Workato',
      'UiPath',
      'Power Automate',
      'Automation Anywhere',
      'Blue Prism',
      'Activepieces',
      'Pipedream',
      'Bardeen',
      'Appsmith',
      'Bubble',
      'Webflow',
      'FlutterFlow',
      'Glide',
      'Softr',
      'Nintex',
      'Tray.io',
      'Boomi',
      'MuleSoft',
      'Apache Camel',
      'Power Apps',
      'Microsoft Power Platform',
      'Google Apps Script',
      'RPA',
      'Robotic Process Automation',
    ],
  },
  {
    label: 'Design',
    items: [
      // UI & Prototyping
      'Figma',
      'Adobe XD',
      'Sketch',
      'Penpot',
      'InVision',
      'Zeplin',
      'Framer',
      'Axure RP',
      'Marvel',
      'ProtoPie',
      'Principle',
      // Adobe Creative Suite
      'Photoshop',
      'Illustrator',
      'InDesign',
      'Adobe Creative Suite',
      'Lightroom',
      // Other Design
      'Canva',
      'CorelDRAW',
      'Affinity Designer',
      'Affinity Photo',
      'Affinity Publisher',
      'Procreate',
      'Spline',
      'Rive',
      'Lottie',
      // Design Systems
      'Storybook',
      'Design Systems',
      'Design Tokens',
      'Atomic Design',
      // UX Methods & Concepts
      'UX Design',
      'UI Design',
      'Wireframing',
      'Prototyping',
      'Accessibility',
      'WCAG',
      'Design Thinking',
      'Information Architecture',
      'User Experience',
      'Interaction Design',
      'Visual Design',
    ],
  },
  {
    label: 'Video',
    items: [
      // Editing
      'Premiere Pro',
      'DaVinci Resolve',
      'Final Cut Pro',
      'CapCut',
      'Vegas Pro',
      'iMovie',
      // Motion & VFX
      'After Effects',
      'Nuke',
      'Houdini',
      'Fusion',
      'Mocha Pro',
      // 3D & Animation
      'Blender',
      'Cinema 4D',
      'Maya',
      '3ds Max',
      'ZBrush',
      'Substance Painter',
      'Substance Designer',
      // Audio
      'Adobe Audition',
      'Logic Pro',
      'Pro Tools',
      'Audacity',
      // AI Video
      'Runway',
      'Sora',
      'Pika',
      'HeyGen',
      'ElevenLabs',
      'Synthesia',
      'Topaz Video AI',
      // Streaming & Production
      'OBS Studio',
      'Streamyard',
      'vMix',
      'Ecamm Live',
    ],
  },
  {
    label: 'Game Dev',
    items: [
      // Engines
      'Unreal Engine',
      'Unity',
      'Godot',
      'Cocos2d',
      'CryEngine',
      'GameMaker',
      'RPG Maker',
      // Graphics APIs
      'OpenGL',
      'DirectX',
      'DirectX 12',
      'Vulkan',
      'Metal',
      'WebGL',
      'WebGPU',
      // Shaders
      'HLSL',
      'GLSL',
      'Shader',
      'ShaderGraph',
      'WGSL',
      // Web 3D
      'Three.js',
      'Babylon.js',
      'PlayCanvas',
      'A-Frame',
      // Game Tools
      'Perforce',
      'Plastic SCM',
      'FMOD',
      'Wwise',
      'Spine',
      'Tiled',
    ],
  },
  {
    label: 'Mobile',
    items: [
      'Flutter',
      'React Native',
      'iOS',
      'Android',
      'SwiftUI',
      'Jetpack Compose',
      'Expo',
      'Capacitor',
      'Kotlin Multiplatform',
      'KMP',
      'Ionic',
      'Xamarin',
      'Cordova',
      'NativeScript',
    ],
  },
  {
    label: 'Embedded & IoT',
    items: [
      'Embedded C',
      'Embedded C++',
      'RTOS',
      'FreeRTOS',
      'Microcontrollers',
      'ARM',
      'FPGA',
      'Verilog',
      'VHDL',
      'Arduino',
      'Raspberry Pi',
      'ESP32',
      'Firmware',
      'PCB Design',
    ],
  },
  {
    label: 'Web3',
    items: [
      'Solidity',
      'EVM',
      'Ethereum',
      'Bitcoin',
      'Web3.js',
      'Ethers.js',
      'Hardhat',
      'Truffle',
      'Smart Contracts',
      'DeFi',
      'NFT',
      'Cosmos',
      'Polkadot',
    ],
  },
  {
    label: 'QA & Testing',
    items: [
      // Unit & Integration
      'Jest',
      'Mocha',
      'Chai',
      'Vitest',
      'Testing Library',
      'JUnit',
      'TestNG',
      'PyTest',
      'RSpec',
      'Go Test',
      // E2E & Browser
      'Cypress',
      'Playwright',
      'Selenium',
      'Puppeteer',
      'WebdriverIO',
      // API Testing
      'Postman',
      'Insomnia',
      'k6',
      'Artillery',
      // Performance
      'JMeter',
      'Gatling',
      'Locust',
      // Mobile Testing
      'Appium',
      'XCTest',
      'Espresso',
      // Cross-Browser
      'BrowserStack',
      'Sauce Labs',
      'LambdaTest',
      // Code Quality
      'SonarQube',
      'ESLint',
      'Prettier',
      'Cucumber',
      'Gherkin',
      // Methodologies
      'TDD',
      'BDD',
      'SDET',
      'Manual Testing',
      'Load Testing',
      'Regression Testing',
    ],
  },
  {
    label: 'Product & Agile',
    items: [
      // Methodology
      'Product Management',
      'Agile',
      'Scrum',
      'Kanban',
      'SAFe',
      'Shape Up',
      'Lean',
      'OKRs',
      'Roadmapping',
      'Product Strategy',
      'Go-to-Market',
      'Product-Led Growth',
      'PLG',
      // Discovery & Research
      'User Research',
      'User Interviews',
      'Usability Testing',
      'Jobs-to-be-Done',
      'JTBD',
      'Customer Discovery',
      // Experimentation
      'A/B Testing',
      'Feature Flags',
      'Hypothesis Testing',
      // Analytics
      'Mixpanel',
      'Amplitude',
      'PostHog',
      'Pendo',
      'FullStory',
      'LogRocket',
      'Heap',
      // Optimization
      'Optimizely',
      'VWO',
      'LaunchDarkly',
      'Split.io',
      // Project & Collab
      'Jira',
      'Confluence',
      'Linear',
      'Notion',
      'Aha!',
      'ProductPlan',
      'Productboard',
      'Monday.com',
      'Asana',
      'ClickUp',
      'Trello',
    ],
  },
  {
    label: 'Marketing',
    items: [
      // SEO
      'SEO',
      'SEM',
      'Technical SEO',
      'On-page SEO',
      'Off-page SEO',
      'Local SEO',
      'AEO',
      'GEO',
      'Link Building',
      'Backlink Analysis',
      'Keyword Research',
      'Core Web Vitals',
      // SEO Tools
      'Ahrefs',
      'Semrush',
      'Moz',
      'Moz Pro',
      'Screaming Frog',
      'Sitebulb',
      'Majestic',
      'STAT',
      'AccuRanker',
      'Surfer SEO',
      'Clearscope',
      'Frase',
      'MarketMuse',
      'Keyword Insights',
      'BrightLocal',
      'BuzzStream',
      'Ubersuggest',
      // Analytics & Reporting
      'Google Analytics',
      'GA4',
      'Google Search Console',
      'Bing Webmaster Tools',
      'Looker Studio',
      'Adobe Analytics',
      'Hotjar',
      'Microsoft Clarity',
      'GTmetrix',
      'PageSpeed Insights',
      // Ads
      'Google Ads',
      'Meta Ads',
      'Facebook Ads',
      'LinkedIn Ads',
      'TikTok Ads',
      'Programmatic Advertising',
      'Display Advertising',
      'PPC',
      // Email & CRM
      'HubSpot',
      'Klaviyo',
      'Mailchimp',
      'ActiveCampaign',
      'Brevo',
      'Drip',
      'Marketo',
      'Pardot',
      'Salesforce Marketing Cloud',
      'Constant Contact',
      // Social & Content
      'Content Strategy',
      'Content Marketing',
      'Copywriting',
      'Buffer',
      'Hootsuite',
      'Sprout Social',
      'Later',
      'Sprinklr',
      'BrandWatch',
      // Growth & CRO
      'Growth Hacking',
      'Growth Marketing',
      'CRO',
      'A/B Testing',
      'Email Marketing',
      'Affiliate Marketing',
      'Influencer Marketing',
      'Performance Marketing',
      // Schema & Structured Data
      'Schema.org',
      'JSON-LD',
      'Structured Data',
      'Rich Snippets',
    ],
  },
  {
    label: 'HR & People',
    items: [
      // ATS
      'Greenhouse',
      'Lever',
      'Workday Recruiting',
      'iCIMS',
      'Taleo',
      'Recruitee',
      'Teamtailor',
      'SmartRecruiters',
      'Jobvite',
      'Bullhorn',
      'Jazz HR',
      'Ashby',
      'Rippling',
      // HRIS / HCM
      'Workday',
      'BambooHR',
      'SAP SuccessFactors',
      'Oracle HCM',
      'ADP',
      'UKG',
      'Personio',
      'Ceridian Dayforce',
      'Paycor',
      'HiBob',
      'Lattice',
      // Payroll
      'Gusto',
      'Rippling',
      'Paychex',
      'ADP Payroll',
      // Performance & Engagement
      'Lattice',
      'Culture Amp',
      'Leapsome',
      '15Five',
      'Glint',
      // Learning
      'Workday Learning',
      'Cornerstone OnDemand',
      'Docebo',
      // Sourcing & Recruitment Marketing
      'LinkedIn Recruiter',
      'LinkedIn Talent Insights',
      'Indeed',
      'ZipRecruiter',
      'Glassdoor',
      'Beamery',
      'SeekOut',
      // Concepts
      'ATS',
      'HRIS',
      'HRMS',
      'HCM',
      'Talent Acquisition',
      'Payroll',
      'Recruiting',
      'Onboarding',
      'Workforce Analytics',
      'Talent Intelligence',
      'People Analytics',
      'Compensation & Benefits',
      'Employee Experience',
    ],
  },
  {
    label: 'Fintech',
    items: [
      // Payment Processing
      'Stripe',
      'Plaid',
      'Braintree',
      'Adyen',
      'Square',
      'PayPal',
      'Razorpay',
      'Checkout.com',
      'Marqeta',
      'Dwolla',
      // Accounting Software
      'QuickBooks',
      'Xero',
      'NetSuite',
      'Sage',
      'SAP B1',
      'FreshBooks',
      'Zoho Books',
      // Financial Modeling & Analysis
      'Bloomberg Terminal',
      'Capital IQ',
      'FactSet',
      'PitchBook',
      'Argus',
      'DCF',
      'Financial Modeling',
      'FP&A',
      'Excel',
      'VBA',
      // Compliance & RegTech
      'IFRS',
      'GAAP',
      'Basel III',
      'AML',
      'KYC',
      'SOX',
      'RegTech',
      // General
      'Fintech',
      'Payment Gateways',
      'Open Banking',
      'Ledger',
      'Accounting',
      'DLT',
      'Blockchain',
      'Digital Banking',
    ],
  },
  {
    label: 'Enterprise',
    items: [
      // CRM
      'Salesforce',
      'HubSpot',
      'Microsoft Dynamics',
      'Zoho CRM',
      'Pipedrive',
      'Freshsales',
      // E-commerce
      'Shopify',
      'Magento',
      'BigCommerce',
      'WooCommerce',
      'Shopify Plus',
      // CMS
      'WordPress',
      'Webflow',
      'Contentful',
      'Sanity',
      'Strapi',
      'Ghost',
      // ERP & Operations
      'SAP',
      'SAP S/4HANA',
      'Oracle ERP',
      'NetSuite',
      'Microsoft Dynamics 365',
      'Odoo',
      'Workday',
      // ITSM
      'ServiceNow',
      'Jira Service Management',
      'Zendesk',
      'Freshdesk',
      'Intercom',
      // Collaboration
      'Slack',
      'Microsoft Teams',
      'Notion',
      'Confluence',
      'Asana',
      'Monday.com',
      'ClickUp',
      'Airtable',
    ],
  },
];

const TECH_KEYWORDS = TECH_CATEGORIES.flatMap((category) => category.items);

const TECH_CATEGORY_MAP = Object.fromEntries(
  TECH_CATEGORIES.flatMap((category) => category.items.map((entry) => [entry, category.label])).map(
    ([name, label]) => [name.toLowerCase(), label],
  ),
);

if (typeof globalThis !== 'undefined') {
  globalThis.TECH_CATEGORIES = TECH_CATEGORIES;
  globalThis.TECH_KEYWORDS = TECH_KEYWORDS;
  globalThis.TECH_CATEGORY_MAP = TECH_CATEGORY_MAP;
  if (typeof globalThis.module !== 'undefined') {
    globalThis.module.exports = {
      TECH_CATEGORIES,
      TECH_KEYWORDS,
      TECH_CATEGORY_MAP,
    };
  }
}
